version: "3"

services:
  sapio_analytics_server:
    build:
      context: sapio_analytics_server
      dockerfile: Dockerfile
    image: sapiosciences/sapio_analytics_server
    environment:
      SAPIO_EXEC_SERVER_API_KEY: Vi6ZGDqhKBieLcDWrNtDpDcmKeNptXZE766Tc4NFCGg4tPgXbq3JmLj3XW7fpopUngv3KEDe69KuhSxEJL4
    volumes:
      - data:/data
    ports:
      - "8686:8686"

volumes:
  data: