version: "3"

services:
  sapio_analytics_server:
    build:
      context: sapio_analytics_server
      dockerfile: Dockerfile
    image: sapiosciences/sapio_analytics_server_dev:24.12
    environment:
      #NOTE: UPDATE ALL OF THESE BEFORE DEPLOYMENT!!!
      SAPIO_EXEC_SERVER_API_KEY: Your API Key. Please see README.
      # If base64 and password is specified here, these keys will be used instead of those in volume.
      SAPIO_EXEC_SERVER_KEYSTORE_PASSWORD: 123456
      SAPIO_EXEC_SERVER_KEYSTORE_BASE64: YOUR_KEYSTORE_BASE64. Please see README.
    volumes:
      - data:/data
    ports:
      - "8686:8686"

volumes:
  data: